---
AWSTemplateFormatVersion: 2010-09-09

Description: >
    This template deploys a Lambda function that can be used with the Segment Amazon Personalize destination in the Personalize and CDP workshops.

Parameters:
  ResourceBucket:
    Type: String
    Description: >
      S3 bucket name where the Retail Demo Store deployment resources are staged (product images, nested CloudFormation templates, source code snapshot, 
      notebooks, deployment Lambda code, etc).

  ResourceBucketRelativePath:
    Type: String
    Description: >
      Optional path in the Deployment Resources Staging bucket where the deployment resources are stored (e.g. path/path2/). 
      Leave blank if resources are at the root of the Staging Resource Bucket. If specified, MUST end with '/'.

Resources:
  SegmentPersonalizeDestinationLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Description: 'Handles events passed from Segment to the Personalize tracker for user-item interactions.'
      Handler: segment-personalize-destination.lambda_handler
      Role: !GetAtt 
        - SegmentPersonalizeDestinationLambdaExecutionRole
        - Arn
      Code:
        S3Bucket: !Ref ResourceBucket
        S3Key: !Sub '${ResourceBucketRelativePath}aws-lambda/segment-personalize-destination.zip'
      Runtime: python3.8
      Timeout: 900
      FunctionName: SegmentPersonalizeDestinationLambdaFunction
      Environment:
        Variables:
          personalize_tracking_id:  ''
          personalize_campaign_arn: ''

  SegmentCrossAccountLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
     AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::595280932656:root"
            Action:
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                "sts:ExternalId": '123456789'
     Path: /
     Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/SegmentPersonalizeDestinationLambdaFunction:log-stream:*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/SegmentPersonalizeDestinationLambdaFunction'
              - Effect: Allow
                Action:
                  - ssm:GetParameter                
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/retaildemostore-*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - personalize:GetRecommendations
                  - personalize:Record
                  - personalize:PutEvents
                Resource: '*'

  SegmentPersonalizeDestinationLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/SegmentPersonalizeDestinationLambdaFunction:log-stream:*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/SegmentPersonalizeDestinationLambdaFunction'
              - Effect: Allow
                Action:
                  - ssm:GetParameter                
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/retaildemostore-*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - personalize:GetRecommendations
                  - personalize:Record
                  - personalize:PutEvents
                Resource: '*'

Outputs:
  LambdaFunctionArn:
    Description: Lambda function ARN for the Segment Personalize destination Lambda function.
    Value: !GetAtt SegmentPersonalizeDestinationLambdaFunction.Arn
